from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

#Group tasks for informatics
inline_kb_tasks = InlineKeyboardMarkup(row_width=3)
inline_kb_task1 = InlineKeyboardButton('1',callback_data='tsk01')
inline_kb_task2 = InlineKeyboardButton('2',callback_data='tsk02')
inline_kb_task3 = InlineKeyboardButton('3',callback_data='tsk03')
inline_kb_task4 = InlineKeyboardButton('4',callback_data='tsk04')
inline_kb_task5 = InlineKeyboardButton('5',callback_data='tsk05')
inline_kb_task6 = InlineKeyboardButton('6',callback_data='tsk06')
inline_kb_task7 = InlineKeyboardButton('7',callback_data='tsk07')
inline_kb_task8 = InlineKeyboardButton('8',callback_data='tsk08')
inline_kb_task9 = InlineKeyboardButton('9',callback_data='tsk09')
inline_kb_task10 = InlineKeyboardButton('10',callback_data='tsk10')
inline_kb_task11 = InlineKeyboardButton('11',callback_data='tsk11')
inline_kb_task12 = InlineKeyboardButton('12',callback_data='tsk12')
inline_kb_task13 = InlineKeyboardButton('13',callback_data='tsk13')
inline_kb_task14 = InlineKeyboardButton('14',callback_data='tsk14')
inline_kb_task15 = InlineKeyboardButton('15',callback_data='tsk15')
inline_kb_task16 = InlineKeyboardButton('16',callback_data='tsk16')
inline_kb_task17 = InlineKeyboardButton('17',callback_data='tsk17')
inline_kb_task18 = InlineKeyboardButton('18',callback_data='tsk18')
inline_kb_task19 = InlineKeyboardButton('19',callback_data='tsk19')
inline_kb_task20 = InlineKeyboardButton('20',callback_data='tsk20')
inline_kb_task21 = InlineKeyboardButton('21',callback_data='tsk21')
inline_kb_task22 = InlineKeyboardButton('22',callback_data='tsk22')
inline_kb_task23 = InlineKeyboardButton('23',callback_data='tsk23')
inline_kb_task24 = InlineKeyboardButton('24',callback_data='tsk24')
inline_kb_task25 = InlineKeyboardButton('25',callback_data='tsk25')
inline_kb_task26 = InlineKeyboardButton('26',callback_data='tsk26')
inline_kb_task27 = InlineKeyboardButton('27',callback_data='tsk27')

inline_kb_tasks.add(inline_kb_task1,inline_kb_task2,inline_kb_task3)
inline_kb_tasks.add(inline_kb_task4,inline_kb_task5,inline_kb_task6)
inline_kb_tasks.add(inline_kb_task7,inline_kb_task8,inline_kb_task9)
inline_kb_tasks.add(inline_kb_task10,inline_kb_task11,inline_kb_task12)
inline_kb_tasks.add(inline_kb_task13,inline_kb_task14,inline_kb_task15)
inline_kb_tasks.add(inline_kb_task16,inline_kb_task17,inline_kb_task18)
inline_kb_tasks.add(inline_kb_task19,inline_kb_task20,inline_kb_task21)
inline_kb_tasks.add(inline_kb_task22,inline_kb_task23,inline_kb_task24)
inline_kb_tasks.add(inline_kb_task25,inline_kb_task26,inline_kb_task27)